apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: banking-staging.trafficreplay.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: banking-frontend
            port:
              number: 80
