apiVersion: v1
kind: Secret
metadata:
  name: banking-kafka-sasl
  namespace: banking-app
type: Opaque
stringData:
  username: banking
  password: banking-secret
  users: banking
  passwords: banking-secret
