apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-app

resources:
- ../../base
- kafka-sasl-secret.yaml

patches:
- path: kafka-sasl-deployment.yaml
- path: transactions-service-kafka-sasl.yaml
- path: notification-service-kafka-sasl.yaml
