apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-notification
  namespace: banking-app
spec:
  template:
    spec:
      containers:
      - name: notification-service
        env:
        - name: KAFKA_SASL_MECHANISM
          value: "PLAIN"
        - name: KAFKA_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: banking-kafka-sasl
              key: username
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banking-kafka-sasl
              key: password
