apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: banking-app
  labels:
    app: grafana
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: observability
    app.kubernetes.io/version: v1.0.0
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger:16686
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: banking-app
  labels:
    app: grafana
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: observability
    app.kubernetes.io/version: v1.0.0
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      folderUid: ''
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
  banking-app-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Banking Application Overview",
        "tags": ["banking-app"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "HTTP Requests per Second",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total[5m])",
                "legendFormat": "{{service}} - {{method}} {{uri}}"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Response Times",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
                "legendFormat": "{{service}} - 95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket[5m]))",
                "legendFormat": "{{service}} - 50th percentile"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "Database Connections",
            "type": "graph",
            "targets": [
              {
                "expr": "hikaricp_connections_active",
                "legendFormat": "{{pool}} - Active Connections"
              },
              {
                "expr": "hikaricp_connections_idle",
                "legendFormat": "{{pool}} - Idle Connections"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "JVM Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "jvm_memory_used_bytes",
                "legendFormat": "{{service}} - {{area}} {{id}}"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          }
        ],
        "time": {"from": "now-1h", "to": "now"},
        "refresh": "5s"
      }
    }