---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: banking-app
  labels:
    app: jaeger
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: observability
    app.kubernetes.io/version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        app.kubernetes.io/name: banking-app
        app.kubernetes.io/component: observability
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.57
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 14268
          name: collector
        - containerPort: 4318
          name: otlp-http
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 5778 # For sampling strategies
          name: sampling
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_OTLP_GRPC_HOST_PORT
          value: ":4317"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: banking-app
  labels:
    app: jaeger
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: observability
    app.kubernetes.io/version: v1.0.0
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: 16686
    name: ui
  - port: 14268
    targetPort: 14268
    name: collector
  - port: 4318
    targetPort: 4318
    name: otlp-http
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
  - port: 5778
    targetPort: 5778
    name: sampling
  selector:
    app: jaeger
