apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: banking-app-observability
  namespace: banking-app

resources:
  - prometheus-deployment.yaml
  - prometheus-config.yaml
  - otel-collector.yaml
  - jaeger-deployment.yaml
  - loki.yaml
  - grafana.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboards-app
    namespace: banking-app
    files:
      - banking-app-health.json=dashboards/banking-app-health.json
  - name: grafana-dashboards-byoc
    namespace: banking-app
    files:
      - speedscale-byoc.json=dashboards/speedscale-byoc.json
      - speedscale-traffic.json=dashboards/speedscale-traffic.json
