apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: banking-app-observability
  namespace: banking-app

resources:
  - prometheus-deployment.yaml
  - prometheus-config.yaml
  - otel-collector.yaml

labels:
  - pairs:
      app.kubernetes.io/name: banking-app
      app.kubernetes.io/component: observability
      app.kubernetes.io/version: v1.0.0
