apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: gateway
    app.kubernetes.io/service: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      app.kubernetes.io/name: banking-app
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/name: banking-app
        app.kubernetes.io/component: gateway
        app.kubernetes.io/service: api-gateway
    spec:
      serviceAccountName: banking-app-sa
      containers:
      - name: api-gateway
        image: ghcr.io/speedscale/microsvc/api-gateway:v1.1.13
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom"
        envFrom:
        - configMapRef:
            name: app-config
        - configMapRef:
            name: api-gateway-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      initContainers:
      - name: wait-for-services
        image: busybox:1.35
        command: ['sh', '-c', 'echo "[api-gateway] Waiting for microservices..."; services="user-service:80 accounts-service:80 transactions-service:80"; for service in $services; do while ! nc -z ${service%:*} ${service#*:}; do echo "[api-gateway] Waiting for $service..."; sleep 1; done; echo "[api-gateway] ✓ $service ready"; done; echo "[api-gateway] All services ready!"']