apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: banking-app
  labels:
    app: frontend
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/service: frontend
    app.kubernetes.io/version: v1.1.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: banking-app
        app.kubernetes.io/component: frontend
        app.kubernetes.io/service: frontend
    spec:
      serviceAccountName: banking-app-sa
      containers:
      - name: frontend
        image: ghcr.io/speedscale/microsvc/frontend:v1.1.8
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: frontend-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3