apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-client
  namespace: banking-app
  labels:
    app: simulation-client
    component: simulation
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: simulation-client
  template:
    metadata:
      labels:
        app: simulation-client
        component: simulation
      annotations:
        # Force restart when config changes
        configmap/checksum: "{{ configmap-checksum }}"
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: banking-app-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: simulation-client
        image: ghcr.io/speedscale/microsvc/simulation-client:v1.3.4
        imagePullPolicy: Always
        
        ports:
        - name: health
          containerPort: 3001
          protocol: TCP
        
        envFrom:
        - configMapRef:
            name: simulation-client-config
        - secretRef:
            name: simulation-client-secret
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        
        # Health checks
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep '[n]ode' | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep '[n]ode' | grep -v grep"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        
        # Graceful shutdown
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 10"
        
        # Temporary directories for writable filesystem
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: home
          mountPath: /home/simulation
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: home
        emptyDir: {}
      
      # DNS configuration
      dnsPolicy: ClusterFirst
      
      # Restart policy
      restartPolicy: Always
      
      # Node selection (optional)
      # nodeSelector:
      #   kubernetes.io/os: linux
      
      # Tolerations (optional)
      # tolerations:
      # - key: "simulation"
      #   operator: "Equal"
      #   value: "true"
      #   effect: "NoSchedule"