apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: microservice
    app.kubernetes.io/service: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      app.kubernetes.io/name: banking-app
      app.kubernetes.io/component: microservice
  template:
    metadata:
      labels:
        app: user-service
        app.kubernetes.io/name: banking-app
        app.kubernetes.io/component: microservice
        app.kubernetes.io/service: user-service
    spec:
      serviceAccountName: banking-app-sa
      containers:
      - name: user-service
        image: ghcr.io/speedscale/microsvc/user-service:v1.3.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user-service-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom"
        envFrom:
        - configMapRef:
            name: app-config
        - configMapRef:
            name: user-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      initContainers:
      - name: wait-for-postgres
        image: postgres:15-alpine
        command: ['sh', '-c', 'echo "[user-service] Waiting for PostgreSQL..."; until pg_isready -h postgres -p 5432 -q; do sleep 1; done; echo "[user-service] PostgreSQL ready!"']