apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: banking-app
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_WIREDTIGER_CACHE_SIZE_GB
              value: "0.25"
          command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            periodSeconds: 10
