apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-accounts
  namespace: banking-app
  annotations:
    capture.speedscale.com/enabled: "true"
    capture.speedscale.com/java-agent: "true"
