apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: banking-app
  annotations:
    sidecar.speedscale.com/inject: "true"
    sidecar.speedscale.com/tls-out: "true"
    sidecar.speedscale.com/tls-java-tool-options: "true"