apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../observability

patches:
# Add Istio injection and Speedscale labels to the existing banking-app namespace
- target:
    version: v1
    kind: Namespace
    name: banking-app
  patch: |-
    - op: add
      path: /metadata/labels/istio-injection
      value: enabled
    - op: add
      path: /metadata/labels/speedscale
      value: "true"
- path: user-service-annotations.yaml
- path: accounts-service-annotations.yaml
- path: transactions-service-annotations.yaml
- path: ai-service-annotations.yaml
- path: api-gateway-annotations.yaml
- path: frontend-annotations.yaml
- path: fraud-service-annotations.yaml
- path: notification-service-annotations.yaml