apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: user-service-annotations.yaml
- path: accounts-service-annotations.yaml
- path: transactions-service-annotations.yaml
- path: api-gateway-annotations.yaml
- path: frontend-annotations.yaml