apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- user-service-annotations.yaml
- accounts-service-annotations.yaml
- transactions-service-annotations.yaml
- api-gateway-annotations.yaml
- frontend-annotations.yaml