apiVersion: v1
kind: Service
metadata:
  name: speedscale-forwarder-metrics
  namespace: speedscale
  labels:
    app.kubernetes.io/name: speedscale
    app.kubernetes.io/component: forwarder-metrics
spec:
  selector:
    app: speedscale-forwarder
    controlplane.speedscale.com/component: forwarder
  ports:
    - port: 4145
      targetPort: 4145
      protocol: TCP
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: speedscale-nettap-metrics
  namespace: speedscale
  labels:
    app.kubernetes.io/name: speedscale
    app.kubernetes.io/component: nettap-metrics
spec:
  selector:
    app: speedscale-nettap
  ports:
    - port: 4145
      targetPort: 4145
      protocol: TCP
      name: metrics
