apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-transactions
  namespace: banking-app
  annotations:
    sidecar.speedscale.com/inject: "false"
    capture.speedscale.com/enabled: "true"
    capture.speedscale.com/java-agent: "true"
