apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: gateway
    app.kubernetes.io/service: api-gateway
spec:
  type: LoadBalancer  # For external access in minikube
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-gateway
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: gateway