apiVersion: v1
kind: Service
metadata:
  name: banking-fraud
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: microservice
    app.kubernetes.io/service: fraud-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  selector:
    app: banking-fraud
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: microservice
