apiVersion: v1
kind: Service
metadata:
  name: transactions-service
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: microservice
    app.kubernetes.io/service: transactions-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: transactions-service
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: microservice