apiVersion: v1
kind: Service
metadata:
  name: banking-user
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: microservice
    app.kubernetes.io/service: user-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: banking-user
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: microservice