apiVersion: v1
kind: Namespace
metadata:
  name: banking-app
  labels:
    name: banking-app
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: banking-app-sa
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: banking-app
  name: banking-app-role
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: banking-app-rolebinding
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: banking-app-sa
  namespace: banking-app
roleRef:
  kind: Role
  name: banking-app-role
  apiGroup: rbac.authorization.k8s.io