spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Health check routes for direct access (higher priority with lower order)
        - id: user-service-health
          uri: ${services.user-service.url}
          order: -1
          predicates:
            - Path=/api/user-service/health
          filters:
            - RewritePath=/api/user-service/health, /actuator/health
        - id: accounts-service-health
          uri: ${services.accounts-service.url}
          order: -1
          predicates:
            - Path=/api/accounts-service/health
          filters:
            - RewritePath=/api/accounts-service/health, /actuator/health
        - id: transactions-service-health
          uri: ${services.transactions-service.url}
          order: -1
          predicates:
            - Path=/api/transactions-service/health
          filters:
            - RewritePath=/api/transactions-service/health, /actuator/health
            
        # Simplified API routes (for frontend compatibility)
        - id: users-simplified
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<path>.*), /user/${path}
        - id: accounts-transactions-simplified
          uri: ${services.accounts-service.url}
          predicates:
            - Path=/api/accounts/*/transactions/**
          filters:
            - RewritePath=/api/accounts/(?<accountId>[^/]+)/transactions/(?<path>.*), /accounts/account/$\{accountId}/transactions/$\{path}
        - id: accounts-transactions-root-simplified
          uri: ${services.accounts-service.url}
          predicates:
            - Path=/api/accounts/*/transactions
          filters:
            - RewritePath=/api/accounts/(?<accountId>[^/]+)/transactions, /accounts/account/$\{accountId}/transactions
        - id: accounts-simplified
          uri: ${services.accounts-service.url}
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/(?<path>.*), /accounts/$\{path}
        - id: transactions-simplified
          uri: ${services.transactions-service.url}
          predicates:
            - Path=/api/transactions/**
          filters:
            - RewritePath=/api/transactions/(?<path>.*), /transactions/$\{path}
            
        # Main service routes (legacy - kept for backward compatibility)
        - id: user-service
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/user-service/**
          filters:
            - RewritePath=/api/user-service/(?<path>.*), /user/$\{path}
        - id: accounts-service
          uri: ${services.accounts-service.url}
          predicates:
            - Path=/api/accounts-service/**
          filters:
            - RewritePath=/api/accounts-service/(?<path>.*), /accounts/$\{path}
        - id: transactions-service
          uri: ${services.transactions-service.url}
          predicates:
            - Path=/api/transactions-service/**
          filters:
            - RewritePath=/api/transactions-service/(?<path>.*), /transactions/$\{path}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 30000
        response-timeout: 60s
  # Redis rate limiter configuration removed - not using rate limiting currently

server:
  port: 8080

# Management and Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

# Service Discovery Configuration
services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  accounts-service:
    url: ${ACCOUNTS_SERVICE_URL:http://localhost:8082}
  transactions-service:
    url: ${TRANSACTIONS_SERVICE_URL:http://localhost:8083}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:banking-app-super-secret-key-change-this-in-production-256-bit}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    com.banking.apigroup: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.actuate.endpoint.web: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
    