apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: byoc-stack
  namespace: byoc-grafana

resources:
  - namespace.yaml
  - grafana.yaml
  - loki.yaml
  - prometheus.yaml
  - otel-collector.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboards-app
    namespace: byoc-grafana
    files:
      - banking-app-health.json=dashboards/banking-app-health.json
  - name: grafana-dashboards-byoc
    namespace: byoc-grafana
    files:
      - speedscale-byoc.json=dashboards/speedscale-byoc.json
      - speedscale-traffic.json=dashboards/speedscale-traffic.json
