apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: secrets
type: Opaque
data:
  password: cGFzc3dvcmQ=  # base64 encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: secrets
type: Opaque
data:
  secret: YmFua2luZy1hcHAtc3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9uLTI1Ni1iaXQ=  # base64 encoded "banking-app-super-secret-key-change-this-in-production-256-bit"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: secrets
type: Opaque
data:
  user-service-password: dXNlcl9zZXJ2aWNlX3Bhc3M=  # base64 encoded "user_service_pass"
  accounts-service-password: YWNjb3VudHNfc2VydmljZV9wYXNz  # base64 encoded "accounts_service_pass"
  transactions-service-password: dHJhbnNhY3Rpb25zX3NlcnZpY2VfcGFzcw==  # base64 encoded "transactions_service_pass"