apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: config
data:
  # Database configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "banking_app"
  
  # Service URLs (for inter-service communication)
  USER_SERVICE_URL: "http://user-service:8080"
  ACCOUNTS_SERVICE_URL: "http://accounts-service:8080"
  TRANSACTIONS_SERVICE_URL: "http://transactions-service:8080"
  
  # Spring profiles
  SPRING_PROFILES_ACTIVE: "docker"
  
  # Observability
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=banking-app"
  
  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_BANKING: "DEBUG"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: config
    app.kubernetes.io/service: user-service
data:
  DB_USERNAME: "user_service_user"
  DB_SCHEMA: "user_service"
  SERVER_PORT: "8080"
  OTEL_SERVICE_NAME: "user-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-service-config
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: config
    app.kubernetes.io/service: accounts-service
data:
  DB_USERNAME: "accounts_service_user"
  DB_SCHEMA: "accounts_service"
  SERVER_PORT: "8080"
  OTEL_SERVICE_NAME: "accounts-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transactions-service-config
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: config
    app.kubernetes.io/service: transactions-service
data:
  DB_USERNAME: "transactions_service_user"
  DB_SCHEMA: "transactions_service"
  SERVER_PORT: "8080"
  OTEL_SERVICE_NAME: "transactions-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: config
    app.kubernetes.io/service: api-gateway
data:
  SERVER_PORT: "8080"
  OTEL_SERVICE_NAME: "api-gateway"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  MANAGEMENT_TRACING_ENABLED: "true"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: config
    app.kubernetes.io/service: frontend
data:
  # Backend API configuration  
  API_GATEWAY_URL: "http://api-gateway:8080"
  
  # OpenTelemetry configuration
  OTEL_SERVICE_NAME: "frontend"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=banking-app"
  
  # Next.js configuration
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"