apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: banking-app
  labels:
    app.kubernetes.io/name: banking-app
    app.kubernetes.io/component: frontend
data:
  NEXT_PUBLIC_API_URL: "http://161.35.253.177"