apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-app

resources:
- ../../base

patches:
- path: user-service-patch.yaml
  target:
    kind: Deployment
    name: user-service
- path: transactions-service-patch.yaml
  target:
    kind: Deployment
    name: transactions-service
- path: accounts-service-patch.yaml
  target:
    kind: Deployment
    name: accounts-service
