apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-app

resources:
- ../../base

images:
- name: ghcr.io/speedscale/microsvc/user-service
  newName: user-service
  newTag: optimized
- name: ghcr.io/speedscale/microsvc/accounts-service
  newName: accounts-service
  newTag: optimized
- name: ghcr.io/speedscale/microsvc/transactions-service
  newName: transactions-service
  newTag: optimized
- name: ghcr.io/speedscale/microsvc/api-gateway
  newName: api-gateway
  newTag: optimized
- name: ghcr.io/speedscale/microsvc/frontend
  newName: frontend
  newTag: optimized

patches:
- target:
    kind: Deployment
    name: user-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
- target:
    kind: Deployment
    name: accounts-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
- target:
    kind: Deployment
    name: transactions-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
- target:
    kind: Deployment
    name: api-gateway
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never 