apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
      - name: user-service
        image: localhost:5000/user-service:v1.1.4
        imagePullPolicy: IfNotPresent
