apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: banking-app
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]
  restartPolicy: Never