apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-tls-repro

resources:
- namespace.yaml
- deployment-noagent.yaml
- deployment-agent.yaml

configMapGenerator:
- name: treasury-client-src
  files:
  - TreasuryClient.java

generatorOptions:
  disableNameSuffixHash: true
