apiVersion: speedscale.com/v1
kind: TrafficReplay
metadata:
  name: replay-banking-transactions
  namespace: banking-app
spec:
  snapshotID: c7bc4b14-40bd-46ae-88fd-f366b36de453
  testConfigID: banking-mock-fail-closed
  mode: responder-only
  workloadRef:
    kind: Deployment
    name: banking-transactions
  cleanup: inventory
