apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../speedscale

patches:
- path: patch-user-service.yaml
- path: patch-accounts-service.yaml
- path: patch-transactions-service.yaml
- path: patch-api-gateway.yaml
